# Generated by Django 5.1.2 on 2024-10-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_operator', '0003_rename_price_per_item_orderitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_spent',
        ),
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
