# Generated by Django 5.1.2 on 2024-10-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_operator', '0004_remove_cart_total_spent_cart_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
    ]
